spring.application.name=progetto_finale_docente
spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleDocente
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

