spring.application.name=progetto_finale_docente
spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleDocente
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

supabase.url=https://ftoklpnnljrzvroohajq.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0b2tscG5ubGpyenZyb29oYWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNzEyMTMsImV4cCI6MjEwNTY0NzIxM30.wXOxK_j_qaCB5UUBSpcNjmy6aUCEqdnZTzl7vULU9sI
supabase.bucket=/storage/v1/object/progetto_finale/
supabase.image=/storage/v1/object/public/progetto_finale/
